export const ADD_POST = 'ADD_POST';
export const START_LOADING_POSTS = "START_LOADING_POSTS";
export const SUCCESSFULLY_LOADED_POSTS = "SUCCESSFULLY_LOADED_POSTS";
export const FAILED_LOADING_POSTS = "FAILED_LOADING_POSTS";