// posts
export const START_LOADING_POSTS = "START_LOADING_POSTS";
export const SUCCESSFULLY_LOADED_POSTS = "SUCCESSFULLY_LOADED_POSTS";
export const SUCCESSFULLY_CREATED_POST = "SUCCESSFULLY_CREATED_POST";

//action happening in /posts/:id/
export const START_LOADING_POST = "START_LOADING_POST";
export const SUCCESSFULLY_LOADED_POST_COMMENTS = "SUCCESSFULLY_LOADED_POST_COMMENTS";

export const ADD_POST = 'ADD_POST'; //not actually happening yet
export const FAILED_LOADING_POSTS = "FAILED_LOADING_POSTS"; //not happening yet


// comments
export const SUCCESSFULLY_CREATED_COMMENT = "SUCCESSFULLY_CREATED_COMMENT";
